### ISSUE TITLE
如何使用 pyinstaller 打包

### ISSUE THREAD

**Issue by carter115** [lich0821/WeChatFerry#275]
**pyinstaller打包exe，运行报错**

打包命令：pyinstaller demo.py

运行：demo.exe

```Traceback (most recent call last):
  File "demo.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "wcferry\__init__.py", line 3, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "wcferry\client.py", line 19, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "pynng\__init__.py", line 3, in <module>
ModuleNotFoundError: No module named '_cffi_backend'
[PYI-17568:ERROR] Failed to execute script 'demo' due to unhandled exception!
```

**使用环境（请补全下列信息）:**
- 操作系统：win11
- 操作系统版本：64位
- Python 版本：39.3.2

**Comment by carter115** [comment]
- **打包命令**

```
pyinstaller --add-binary "C:/Users/Xxxxxx/miniconda3/envs/Xxxxx/Lib/site-packages/wcferry/sdk.dll;wcferry" --add-binary "C:/Users/Xxxxxx/miniconda3/envs/Xxxxx/Lib/site-packages/wcferry/spy.dll;wcferry" --add-binary "C:/Users/Xxxxxx/miniconda3/envs/Xxxxx/Lib/site-packages/wcferry/spy_dev.dll;wcferry" --add-binary "C:/Users/Xxxxxx/miniconda3/envs/Xxxxx/Lib/site-packages/wcferry/spy_debug.dll;wcferry" --hidden-import=_cffi_backend main.py
```

`--hidden-import` 导入模块 `_cffi_backend`
`--add-binary` 添加dll文件

- **检查目录下的文件已经存在** 

`_cffi_backend`, `sdk.dll`,  `spy.dll`,  `spy_dev.dll`,  `spy_debug.dll`,

```
└─main
    │  main.exe
    │
    └─_internal
        │  ......
        │  _cffi_backend.cp311-win_amd64.pyd
        │
        │  ......
        │
        ├─pynng
        │      _nng.pyd
        │
        ├─wcferry
        │  │  sdk.dll
        │  │  spy.dll
        │  │  spy_debug.dll
        │  │  spy_dev.dll
        │  │
        │  └─.dl
```

**Comment by 178me** [comment]
这样子更简单一些
pyinstaller -F --add-data "wcferry;wcferry" --hidden-import _cffi_backend main.py

**Comment by wssnail** [comment]
> 这样子更简单一些 pyinstaller -F --add-data "wcferry;wcferry" --hidden-import _cffi_backend main.py

提示没有声明文件，这个可以添加到哪里

**Comment by liupcoder** [comment]
免责声明文件读取失败
