### ISSUE TITLE
[🐛BUG]  Failed to build installable wheels for some pyproject.toml based projects (pynng)

### ISSUE THREAD

**Issue by MemoryCollection** [lich0821/WeChatFerry#287]
```

(.venv) D:\项目文件\weixin>pip install --upgrade wcferry
Looking in indexes: https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
Collecting wcferry
  Using cached https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages/32/af/646022b00b7c93b44353e91bcc2bddf11375d5bfd90c7bc82ff23699f77a/wcferry-39.3.3.2-py3-none-any.whl (2.1 MB)
Requirement already satisfied: setuptools in d:\项目文件\weixin\.venv\lib\site-packages (from wcferry) (75.6.0)
Collecting grpcio-tools (from wcferry)
  Using cached https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages/ca/d3/9edb57f65f2950920efdf726a8c8b82f65bcde5ccf861a686060ca6512f3/grpcio_tools-1.68.1-cp313-cp313-win_amd64.whl (1.1 MB)
Collecting pynng (from wcferry)
  Using cached https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages/42/e4/72d82060718a133f846cd235e6324a5c3f4367beb292fd503905c010d3e1/pynng-0.8.0.tar.gz (6.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting requests (from wcferry)
  Using cached https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages/f9/9b/335f9764261e915ed497fcdeb11df5dfd6f7bf257d4a6a2a686d80da4d54/requests-2.32.3-py3-none-any.whl (64 kB)
Collecting protobuf<6.0dev,>=5.26.1 (from grpcio-tools->wcferry)
  Using cached https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages/e3/33/dc7a7712f457456b7e0b16420ab8ba1cc8686751d3f28392eb43d0029ab9/protobuf-5.29.1-cp310-abi3-win_amd64.whl (434 kB)
Collecting grpcio>=1.68.1 (from grpcio-tools->wcferry)
  Using cached https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages/7e/d1/3bef33a3d5d26d4ea9284e1b464f481d6d21ed8ae1c3da381b05f62c701d/grpcio-1.68.1-cp313-cp313-win_amd64.whl (4.4 MB)
Collecting cffi (from pynng->wcferry)
  Using cached https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages/7c/fc/6a8cb64e5f0324877d503c854da15d76c1e50eb722e320b15345c4d0c6de/cffi-1.17.1-cp313-cp313-win_amd64.whl (182 kB)
Collecting sniffio (from pynng->wcferry)
  Using cached https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages/e9/44/75a9c9421471a6c4805dbf2356f7c181a29c1879239abab1ea2cc8f38b40/sniffio-1.3.1-py3-none-any.whl (10 kB)
Collecting charset-normalizer<4,>=2 (from requests->wcferry)
  Using cached https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages/65/97/fc9bbc54ee13d33dc54a7fcf17b26368b18505500fc01e228c27b5222d80/charset_normalizer-3.4.0-cp313-cp313-win_amd64.whl (102 kB)
Collecting idna<4,>=2.5 (from requests->wcferry)
  Using cached https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages/76/c6/c88e154df9c4e1a2a66ccf0005a88dfb2650c1dffb6f5ce603dfbd452ce3/idna-3.10-py3-none-any.whl (70 kB)
Collecting urllib3<3,>=1.21.1 (from requests->wcferry)
  Using cached https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages/ce/d9/5f4c13cecde62396b0d3fe530a50ccea91e7dfc1ccf0e09c228841bb5ba8/urllib3-2.2.3-py3-none-any.whl (126 kB)
Collecting certifi>=2017.4.17 (from requests->wcferry)
  Using cached https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages/a5/32/8f6669fc4798494966bf446c8c4a162e0b5d893dff088afddf76414f70e1/certifi-2024.12.14-py3-none-any.whl (164 kB)
Collecting pycparser (from cffi->pynng->wcferry)
  Using cached https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages/13/a3/a812df4e2dd5696d1f351d58b8fe16a405b234ad2886a0dab9183fb78109/pycparser-2.22-py3-none-any.whl (117 kB)
Building wheels for collected packages: pynng
  Building wheel for pynng (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pynng (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [152 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-313\pynng
      copying pynng\exceptions.py -> build\lib.win-amd64-cpython-313\pynng
      copying pynng\nng.py -> build\lib.win-amd64-cpython-313\pynng
      copying pynng\options.py -> build\lib.win-amd64-cpython-313\pynng
      copying pynng\sockaddr.py -> build\lib.win-amd64-cpython-313\pynng
      copying pynng\tls.py -> build\lib.win-amd64-cpython-313\pynng
      copying pynng\_aio.py -> build\lib.win-amd64-cpython-313\pynng
      copying pynng\_version.py -> build\lib.win-amd64-cpython-313\pynng
      copying pynng\__init__.py -> build\lib.win-amd64-cpython-313\pynng
      running egg_info
      writing pynng.egg-info\PKG-INFO
      writing dependency_links to pynng.egg-info\dependency_links.txt
      writing requirements to pynng.egg-info\requires.txt
      writing top-level names to pynng.egg-info\top_level.txt
      ERROR setuptools_scm._file_finders.git listing git files failed - pretending there aren't any
      reading manifest file 'pynng.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.bat'
      warning: no files found matching '8.txt'
      no previously-included directories found matching 'nng\build'
      no previously-included directories found matching 'nng\.git'
      no previously-included directories found matching 'nng\.circleci'
      warning: no previously-included files found matching 'nng\.gitignore'
      no previously-included directories found matching 'mbedtls\build'
      no previously-included directories found matching 'mbedtls\.git'
      no previously-included directories found matching 'mbedtls\.github'
      no previously-included directories found matching 'mbedtls\.travis.yml'
      no previously-included directories found matching 'mbedtls\prefix'
      warning: no previously-included files found matching 'mbedtls\.gitignore'
      adding license file 'LICENSE.txt'
      writing manifest file 'pynng.egg-info\SOURCES.txt'
      running build_ext
      generating cffi module 'build\\temp.win-amd64-cpython-313\\Release\\pynng._nng.c'
      creating build\temp.win-amd64-cpython-313\Release
      running build_mbedtls
      building mbedtls with: ['cmake', '-DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true', '-A', 'x64', '-DENABLE_PROGRAMS=OFF', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=../prefix', '-DENABLE_TESTING=OFF', '..']
      -- Building for: NMake Makefiles
      CMake Deprecation Warning at CMakeLists.txt:21 (cmake_minimum_required):
        Compatibility with CMake < 3.10 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
        to tell CMake that the project requires at least <min> but has been updated
        to work with policies introduced by <max> or earlier.


      CMake Error at CMakeLists.txt:39 (project):
        Generator

          NMake Makefiles

        does not support platform specification, but platform

          x64

        was specified.


      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "D:\项目文件\weixin\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "D:\项目文件\weixin\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\项目文件\weixin\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                              metadata_directory)
                                              ^^^^^^^^^^^^^^^^^^^
        File "C:\Users\dong\AppData\Local\Temp\pip-build-env-3qc3w5i9\overlay\Lib\site-packages\setuptools\build_meta.py", line 438, in build_wheel
          return _build(['bdist_wheel', '--dist-info-dir', str(metadata_directory)])
        File "C:\Users\dong\AppData\Local\Temp\pip-build-env-3qc3w5i9\overlay\Lib\site-packages\setuptools\build_meta.py", line 426, in _build
          return self._build_with_temp_dir(
                 ~~~~~~~~~~~~~~~~~~~~~~~~~^
              cmd,
              ^^^^
          ...<3 lines>...
              self._arbitrary_args(config_settings),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "C:\Users\dong\AppData\Local\Temp\pip-build-env-3qc3w5i9\overlay\Lib\site-packages\setuptools\build_meta.py", line 407, in _build_with_temp_dir
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\dong\AppData\Local\Temp\pip-build-env-3qc3w5i9\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 180, in <module>
        File "C:\Users\dong\AppData\Local\Temp\pip-build-env-3qc3w5i9\overlay\Lib\site-packages\setuptools\__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\dong\AppData\Local\Temp\pip-build-env-3qc3w5i9\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 183, in setup
          return run_commands(dist)
        File "C:\Users\dong\AppData\Local\Temp\pip-build-env-3qc3w5i9\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 199, in run_commands
          dist.run_commands()
          ~~~~~~~~~~~~~~~~~^^
        File "C:\Users\dong\AppData\Local\Temp\pip-build-env-3qc3w5i9\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 954, in run_commands
          self.run_command(cmd)
          ~~~~~~~~~~~~~~~~^^^^^
        File "C:\Users\dong\AppData\Local\Temp\pip-build-env-3qc3w5i9\overlay\Lib\site-packages\setuptools\dist.py", line 995, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\dong\AppData\Local\Temp\pip-build-env-3qc3w5i9\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "C:\Users\dong\AppData\Local\Temp\pip-build-env-3qc3w5i9\overlay\Lib\site-packages\setuptools\command\bdist_wheel.py", line 381, in run
          self.run_command("build")
          ~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\dong\AppData\Local\Temp\pip-build-env-3qc3w5i9\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\dong\AppData\Local\Temp\pip-build-env-3qc3w5i9\overlay\Lib\site-packages\setuptools\dist.py", line 995, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\dong\AppData\Local\Temp\pip-build-env-3qc3w5i9\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "C:\Users\dong\AppData\Local\Temp\pip-build-env-3qc3w5i9\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
          ~~~~~~~~~~~~~~~~^^^^^^^^^^
        File "C:\Users\dong\AppData\Local\Temp\pip-build-env-3qc3w5i9\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\dong\AppData\Local\Temp\pip-build-env-3qc3w5i9\overlay\Lib\site-packages\setuptools\dist.py", line 995, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\dong\AppData\Local\Temp\pip-build-env-3qc3w5i9\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "C:\Users\dong\AppData\Local\Temp\pip-build-env-3qc3w5i9\overlay\Lib\site-packages\cffi\setuptools_ext.py", line 142, in run
          base_class.run(self)
          ~~~~~~~~~~~~~~^^^^^^
        File "<string>", line 170, in run
        File "C:\Users\dong\AppData\Local\Temp\pip-build-env-3qc3w5i9\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\dong\AppData\Local\Temp\pip-build-env-3qc3w5i9\overlay\Lib\site-packages\setuptools\dist.py", line 995, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\dong\AppData\Local\Temp\pip-build-env-3qc3w5i9\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "<string>", line 72, in run
        File "C:\Program Files\Python313\Lib\subprocess.py", line 419, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '-DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true', '-A', 'x64', '-DENABLE_PROGRAMS=OFF', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=../prefix', '-DENABLE_TESTING=OFF', '..']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pynng
Failed to build pynng
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pynng)

(.venv) D:\项目文件\weixin>
```

**使用环境（请补全下列信息）:**
- 操作系统：Windows 10 22H2
- 操作系统版本：64
- Python 版本：Python 3.13.1 

**屏幕截图**
添加屏幕截图以帮助解释您的问题。（可选）

**崩溃信息**
微信崩溃原因描述文件内容。（可选）

**Comment by lich0821** [comment]
[Quick Start](https://github.com/lich0821/WeChatRobot?tab=readme-ov-file#quick-start)

**Comment by MemoryCollection** [comment]
> [Quick Start](https://github.com/lich0821/WeChatRobot?tab=readme-ov-file#quick-start)

文档没找到这个问题，安装依赖失败。

**Comment by lich0821** [comment]
> > [Quick Start](https://github.com/lich0821/WeChatRobot?tab=readme-ov-file#quick-start)
> 
> 文档没找到这个问题，安装依赖失败。

<img width="527" alt="image" src="https://github.com/user-attachments/assets/d18d1d49-f7a7-474f-834d-12e505808458" />
