### ISSUE TITLE
[🐛启动错误] 启动时提示 Stream removed 错误

### ISSUE THREAD

**Issue by minqike** [lich0821/WeChatFerry#3]
**描述这个 bug**
启动时提示 Stream removed 错误

**使用环境（请补全下列信息）：**
- 操作系统： Windows 7
- 操作系统版本： 64 位
- Python 版本 3.7.9

**崩溃信息**
C:\Users\min\Documents\code\python\WeChatRobot-master>C:\Python\Python37_32\pyth
on.exe -V
Python 3.7.9

C:\Users\min\Documents\code\python\WeChatRobot-master>C:\Python\Python37_32\pyth
on.exe main.py
Traceback (most recent call last):
  File "main.py", line 51, in <module>
    main()
  File "main.py", line 26, in main
    wcf = Wcf()
  File "C:\Python\Python37_32\lib\site-packages\wcferry\client.py", line 75, in
__init__
    self.self_wxid = self.get_self_wxid()
  File "C:\Python\Python37_32\lib\site-packages\wcferry\client.py", line 108, in
 get_self_wxid
    rsp = self._stub.RpcGetSelfWxid(wcf_pb2.Empty())
  File "C:\Python\Python37_32\lib\site-packages\grpc\_channel.py", line 946, in
__call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Python\Python37_32\lib\site-packages\grpc\_channel.py", line 849, in
_end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:

        status = StatusCode.UNKNOWN
        details = "Stream removed"
        debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:10
086 {created_time:"2022-11-22T03:39:56.873238164+00:00", grpc_status:2, grpc_mes
sage:"Stream removed"}"
>

**Comment by lich0821** [comment]
这现象的原因是gRPC没启动起来，可能是注入失败了，也可能是注入成功但是微信崩溃了。
- 是否安装后第一次启动就出现？
- 重启微信后能否解决？（使用任务管理器，杀掉微信进程）
- 直接运行 [最新发布](https://github.com/lich0821/WeChatFerry/releases/latest) 里的 `cpp.exe` 是否正常？

**Comment by minqike** [comment]
每次都是微信崩溃了. 重启微信,重启系统都没有用, 
运行cpp.exe也报错

![111](https://user-images.githubusercontent.com/26165564/203239162-bd2bed69-d834-4885-a7a5-7c6af711fbcf.png)

**Comment by maskkid** [comment]
把ipv6禁用掉，使用ipv4应该就行，之前碰到过。
