### ISSUE TITLE
[🐛BUG] pyauto运行报错

### ISSUE THREAD

**Issue by klj218** [lich0821/WeChatFerry#75]
2023-10-08 14:06:23,316 开始初始化...
Exception ignored in: <function Wcf.__del__ at 0x000000000355EC10>
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\paddle_env\lib\site-packages\wcferry\client.py", line 111, in __del__
    self.cleanup()
  File "D:\ProgramData\Anaconda3\envs\paddle_env\lib\site-packages\wcferry\client.py", line 115, in cleanup
    if not self._is_running:
AttributeError: 'WcfV2' object has no attribute '_is_running'
Traceback (most recent call last):
  File "f:/stockstar/project/python/WeChatFerry-master/clients/pyauto/demo.py", line 79, in <module>
    main()
  File "f:/stockstar/project/python/WeChatFerry-master/clients/pyauto/demo.py", line 14, in main
    receiver = Register()
  File "f:\stockstar\project\python\WeChatFerry-master\clients\pyauto\wcfauto\auto_res\bot.py", line 18, in __init__
    self._wcf = Wcf(debug=debug, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'host'

**Comment by lich0821** [comment]
晚点儿 Maintainer 会修复，临时方案：
```py
# 将demo.py 14行的
receiver = Register()
# 修改为：
receiver = Register(host=None)
```

**Comment by yang0961** [comment]
新提交的代码中已经解决了这个问题
